### ISSUE TITLE
Add Wireshark and ns-3 to the test harness.

### ISSUE THREAD

**Issue by xvzcf** [xvzcf/tls-interop-runner#3]
- ns-3 will let us run performance benchmarks while being able to vary parameters such as packet loss and latency
- ns-3 will also let us possibly simulate interesting TLS edge cases
- With ns-3's packet capture, tshark can then decrypt the packets using an SSL keylog file, and the packets can then be examined for verifying whether the handshake on the wire corresponds to what is expected by the testcases

**Comment by cjpatton** [comment]
Addressed by #15 and #24.
