### ISSUE TITLE
Project needs a LICENSE file

### ISSUE THREAD

**Issue by dmcardle** [xvzcf/tls-interop-runner#32]
This is a terribly boring issue, but unfortunately it's blocking me from contributing patches.

**Comment by xvzcf** [comment]
We were thinking MIT for anything that hasn't been pulled in from other projects. Would this work for you?

**Comment by dmcardle** [comment]
Yep, MIT works great!

**Comment by xvzcf** [comment]
Addressed by https://github.com/xvzcf/tls-interop-runner/pull/34
